export const ADD_SEARCH_DATA = 'ADD_SEARCH_DATA';
export const ADD_ADVANTAGES_LINK = 'ADD_ADVANTAGES_LINK';
export const ADD_COUNTRY = 'ADD_COUNTRY';
export const ADD_TOUR = 'ADD_TOUR';
// export const ADD_FLIGHT = 'ADD_FLIGHT';
export const ADD_TICKET = 'ADD_TICKET';
export const CLEAR_TICKET = 'CLEAR_TICKET';
// export const FETCH_FLIGHT = 'FETCH_FLIGHT';
// export const FETCH_FLIGHT_LOADING = 'FETCH_FLIGHT_LOADING';
export const STARTED_FETCH_FLIGHTS = 'STARTED_FETCH_FLIGHTS';
export const FAILED_FETCH_FLIGHTS = 'FAILED_FETCH_FLIGHTS';


export const ADD_TOUR_REQUEST = 'ADD_TOUR_REQUEST';
export const ADD_TOUR_SUCCESS = 'ADD_TOUR_SUCCESS';
export const ADD_TOUR_FAILURE = 'ADD_TOUR_FAILURE';
export const ADD_FLIGHTS_REQUEST = 'ADD_FLIGHTS_REQUEST';
export const ADD_FLIGHT_SUCCESS = 'ADD_FLIGHT_SUCCESS';
export const ADD_FLIGHT_FAILURE = 'ADD_FLIGHT_FAILURE';
export const ADD_ADVANTAGES = 'ADD_ADVANTAGES';
